name: BLU-e
favicon: null
layout_spectrum: 0.5772755932994187
typography_spectrum: 0.55711
title: BLU-e Transformational Frequency Energy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aaaaff'
    - '#d5d5ff'
    - '#0056d6'
    - '#80ffff'
  brandStrength: 0.7653248605784029
  lightness: 0.7727715058717877
  saturation: 0.18356867390684783
  rhythmicContrast: 0.8576939580962062
purpose: []
